import type { Metadata } from 'next';
import '../globals.css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // optional: control boldness
  variable: '--font-poppins', // optional for Tailwind
});

export const metadata: Metadata = {
  title: 'Blog Site',
  description: 'Generated by create next app',
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="flex-1  max-w-5xl mx-auto px-6 lg:px-4 py-10 w-full">
        {children}
      </main>
      <Footer />
    </>
  );
}
