import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Footer from './components/Footer';
import { Poppins } from 'next/font/google';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // optional: control boldness
  variable: '--font-poppins', // optional for Tailwind
});

export const metadata: Metadata = {
  title: 'Blog Site',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased min-h-screen flex flex-col bg-white  dark:bg-black dark:text-white text-black `}
      >
        <Header />
        <main className="flex-1  max-w-5xl mx-auto px-6 lg:px-4 py-10 w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
